# PostgreSQL production config
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nerve_development

test:
  <<: *default
  database: nerve_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: nerve_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: nerve_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: nerve_production_cable
    migrations_paths: db/cable_migrate
