# PostgreSQL production config
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432") %>/nerve_development
  queue:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432") %>/nerve_development
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432") %>/nerve_development
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432") %>/nerve_development
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: nerve_test
  queue:
    <<: *default
    database: nerve_test
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: nerve_test
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: nerve_test
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL") { ENV.fetch("DATABASE_URL", "").gsub(/nerve_production/, "nerve_production_cache") } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL") { ENV.fetch("DATABASE_URL", "").gsub(/nerve_production/, "nerve_production_queue") } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL") { ENV.fetch("DATABASE_URL", "").gsub(/nerve_production/, "nerve_production_cable") } %>
    migrations_paths: db/cable_migrate
